### ISSUE TITLE
Does not work (PopOS)

### ISSUE THREAD

**Issue by MulverineX** [Figma-Linux/figma-linux-font-helper#17]
![image](https://user-images.githubusercontent.com/12068027/118214178-8356da00-b42c-11eb-94fc-e9b3430f8f58.png)
![image](https://user-images.githubusercontent.com/12068027/118214211-9073c900-b42c-11eb-8d3e-b51bc38db4ef.png)

**Comment by ChugunovRoman** [comment]
"disabled Brave on the site and it works"

**Comment by marchellodev** [comment]
Disabling brave shields also did it for me!

If you face the same problem, also make sure the service is running in the background without any erros

![image](https://user-images.githubusercontent.com/61112084/150417019-c2647a44-435c-4cd2-a7b8-81c787d7de08.png)
