### ISSUE TITLE
not able to use local fonts 

### ISSUE THREAD

**Issue by NeerajLehar** [Figma-Linux/figma-linux-font-helper#19]
hello I am not able to use my system local fonts I am using ubuntu 20.4

**Comment by NeerajLehar** [comment]
have to create a link to the local font in the figmaHelper JSON file

**Comment by diegosomar** [comment]
1. In your home directory, create a new directory named Fonts;
2. Put your custom fonts in this new directory;
3. Open the terminal app, past this `sudo nano /etc/figma-linux/fonthelper` and press `ENTER` (put your password and press `ENTER` again;
4. You got a code like that:

```
{
  "port": "111111",
  "directories": [
    "/usr/share/fonts",
    "/root/.local/share/fonts"
  ]
}
```

5. Add one more line, with the path to your new Fonts directory. The final code will be like that:

```
{
  "port": "111111",
  "directories": [
    "/usr/share/fonts",
    "/root/.local/share/fonts",
    "/home/yourusername/Fonts/"
  ]
}
```

Remember to change yourusername to your system user name AND to put a comma after the line 5;

6. Press `CTRL + X` to close and Y to save;
7. Still in the terminal, past this line `sudo systemctl restart fonthelper.service` and press `ENTER`;

The font service will be restarted and your custom fonts are now available in Figma web.
