### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by minnix** [Figma-Linux/figma-linux-font-helper#20]
Font helper is not working on elementary OS 6 Odin.

**Comment by minnix** [comment]
Not working on elementary OS 6 Odin

**Comment by phun-ky** [comment]
Same in my end, 18.04 with same config ad @danielfeather but no local fonts in figma linux :(

**Comment by danielfeather** [comment]
@phun-ky Some ideas that might help with troubleshooting. Try and simulate what Figma will try and do to get the list of fonts and the specific font files. The Font Helper is a HTTP service so you can simulate the HTTP requests that Figma will perform to get a list of local fonts and download the font file when requested. You can try the requests in your browser of choice and it should respond just fine.

From looking at the source code this is the endpoint that Figma will use to get a list of local fonts. So if your not seeing your local fonts in the list then I would try this endpoint and see what you get.
List fonts: ```http://localhost:18412/figma/font-files```
Response
```
{
    "version": 4,
    "fontFiles": {
        "/home/danielfeather/.local/share/fonts/NeueHaasDisplayRoman.ttf": [
            {
                "family": "Neue Haas Grotesk Display Pro",
                "id": "Neue Haas Grotesk Display Pro",
                "italic": false,
                "postscript": "NeueHaasDisplay-Roman",
                "stretch": 5,
                "style": "55 Roman",
                "weight": 400
            }
        ],
```

Get specific font file: ```http://localhost:18412/figma/font-file?file=/home/danielfeather/.local/share/fonts/NeueHaasDisplayRoman.ttf```
Response is the raw font file with a content type of ```application/octet-stream```

I would try these endpoints and see if the fonts you seek are listed and can be read by Figma.

Hope this helps 😄

**Comment by ChamkhiAnas** [comment]
> Hope this helps 😄

i did configure the font helper with my font folder and the agent is running properly when i do 
http://localhost:18412/figma/font-files
it returns my local fonts

but in the web figma no local font is loaded , do u have any idea abt this ?

**Comment by danielfeather** [comment]
> > Hope this helps 😄
> 
> i did configure the font helper with my font folder and the agent is running properly when i do 
> http://localhost:18412/figma/font-files
> it returns my local fonts
> 
> but in the web figma no local font is loaded , do u have any idea abt this ? 

One thing that Figma has done in the last year or so is when you are running it in browser, Figma will check the OS via the user agent string (see #42). 

I would suggest installing a browser extension to spoof your user agent, so Figma thinks you are running on macOS or Windows.

This is the method I use, and it works for me.
